import { StyleSheet, Image, FlatList, TouchableOpacity, ScrollView, Alert, Linking, Modal } from 'react-native';
import { Text, View } from '@/components/Themed';
import React, { useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import Colors from '@/constants/Colors';
import { api } from '@/constants/api';

import { useAuth } from '@/context/AuthContext';

export default function GeneratedPlaylistScreen() {
    const params = useLocalSearchParams();
    const router = useRouter();
    const theme = Colors['dark'];

    // Parse the data passed from Generate
    const playlistData = params.data ? JSON.parse(params.data as string) : null;
    const { spotifyLinked, googleLinked, loginWithSpotify, loginWithGoogle } = useAuth();

    const [selectedTrack, setSelectedTrack] = useState<any>(null);
    const [modalVisible, setModalVisible] = useState(false);

    if (!playlistData) {
        return (
            <View style={styles.container}>
                <Text style={{ color: 'white' }}>No playlist data found.</Text>
            </View>
        );
    }

    const { playlist_name, description, tracks, total_duration_mins } = playlistData;

    const handleTrackPress = (track: any) => {
        setSelectedTrack(track);
        setModalVisible(true);
    };

    const playOnSpotify = async () => {
        if (!selectedTrack) return;
        const url = selectedTrack.external_urls?.spotify || `https://open.spotify.com/track/${selectedTrack.id}`;
        const canOpen = await Linking.canOpenURL(url);
        if (canOpen) {
            Linking.openURL(url);
        } else {
            Alert.alert("Error", "Cannot open Spotify.");
        }
        setModalVisible(false);
    };

    const playOnYouTube = () => {
        if (!selectedTrack) return;
        const query = `${selectedTrack.name} ${selectedTrack.artists[0].name}`;
        const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
        Linking.openURL(url);
        setModalVisible(false);
    };

    const handleSave = async () => {
        try {
            const res = await api.post('/api/playlists', {
                name: playlist_name,
                description,
                tracks: tracks,
                mood: 'generated', // Default mood tag for now
                coverImage: playlistData.coverImage || tracks[0]?.album?.images[0]?.url // Pass cover image
            });

            if (res.error) {
                Alert.alert("Error", res.message || "Failed to save playlist.");
            } else {
                Alert.alert("Saved!", "Playlist added to your profile.");
            }
        } catch (e) {
            Alert.alert("Error", "Could not save playlist.");
        }
    };

    const handleSaveToSpotify = async () => {
        if (!spotifyLinked) {
            loginWithSpotify();
            return;
        }

        console.log("Save to Spotify clicked");
        try {
            const trackUris = tracks.map((t: any) => t.uri).filter((uri: any) => uri);
            if (trackUris.length === 0) {
                Alert.alert("Error", "No valid Spotify tracks found to save.");
                return;
            }

            Alert.alert("Saving...", "Creating your Spotify playlist.");
            const res = await api.post('/spotify/playlist', {
                name: `VibeMixer: ${playlist_name}`,
                description: description || "Generated by VibeMixer",
                trackUris,
                coverImageUrl: tracks[0]?.album?.images[0]?.url
            });

            // Improved Error Check
            if (res.error) {
                const errorMsg = typeof res.error === 'string' ? res.error : (res.message || "Unknown error");

                if (errorMsg.toLowerCase().includes("auth") || errorMsg.includes("401") || errorMsg.toLowerCase().includes("login")) {
                    Alert.alert(
                        "Spotify Not Connected",
                        "Please verify your Spotify account to save playlists.",
                        [
                            { text: "Cancel", style: "cancel" },
                            { text: "Connect", onPress: loginWithSpotify }
                        ]
                    );
                } else {
                    Alert.alert("Spotify Error", errorMsg);
                }
            } else {
                Alert.alert("Success!", "Playlist saved to your Spotify account.");
            }
        } catch (e) {
            Alert.alert("Error", "Failed to connect to Spotify service.");
        }
    };

    const handleSaveToYouTube = async () => {
        if (!googleLinked) {
            loginWithGoogle();
            return;
        }

        try {
            Alert.alert("Saving...", "Creating your YouTube playlist (this may take a moment).");
            const res = await api.post('/youtube/playlist', {
                name: `VibeMixer: ${playlist_name}`,
                description: description || "Generated by VibeMixer",
                tracks: tracks
            });

            if (res.error) {
                const errorMsg = typeof res.error === 'string' ? res.error : (res.message || "Unknown error");

                if (errorMsg.toLowerCase().includes("auth") || errorMsg.includes("401") || errorMsg.toLowerCase().includes("login")) {
                    Alert.alert(
                        "YouTube Not Connected",
                        "Please verify your Google account to save playlists.",
                        [
                            { text: "Cancel", style: "cancel" },
                            { text: "Connect", onPress: loginWithGoogle }
                        ]
                    );
                } else {
                    Alert.alert("YouTube Error", errorMsg);
                }
            } else {
                Alert.alert("Success!", `Playlist saved to YouTube!`);
            }
        } catch (e) {
            Alert.alert("Error", "Failed to connect to YouTube service.");
        }
    };

    const handleShare = () => {
        // In a real app with native modules, using react-native-view-shot would be ideal here.
        // For now, we simulate the action.
        Alert.alert("Share Story", "Opening Instagram Stories with your vibe card... \n(Placeholder: Implementation requires native view-shot module)");
    };

    const renderHeader = () => (
        <View style={styles.headerContainer}>
            <LinearGradient
                colors={['#4c1d95', '#000000']}
                style={StyleSheet.absoluteFill}
                start={{ x: 0.5, y: 0 }}
                end={{ x: 0.5, y: 1 }}
            />
            {/* ... Refine Button ... */}
            <TouchableOpacity
                style={styles.refineButton}
                activeOpacity={0.8}
                onPress={() => router.push('/(tabs)/swipe')}
            >
                <LinearGradient
                    colors={['#8B5CF6', '#6D28D9']}
                    start={{ x: 0, y: 0 }}
                    end={{ x: 1, y: 0 }}
                    style={styles.refineGradient}
                >
                    <FontAwesome name="sliders" size={16} color="white" style={{ marginRight: 8 }} />
                    <Text style={styles.refineText}>Refine Your Vibe</Text>
                </LinearGradient>
            </TouchableOpacity>

            <View style={styles.headerContent}>
                {/* Album Art Placeholder or from first track */}
                {/* Album Art (Pollinations or Spotify) */}
                <View style={styles.albumArtContainer}>
                    {playlistData.coverImage ? (
                        <Image source={{ uri: playlistData.coverImage }} style={styles.albumArt} />
                    ) : tracks[0]?.album?.images[0]?.url ? (
                        <Image source={{ uri: tracks[0].album.images[0].url }} style={styles.albumArt} />
                    ) : (
                        <View style={[styles.albumArt, { backgroundColor: '#333', justifyContent: 'center', alignItems: 'center' }]}>
                            <FontAwesome name="music" size={40} color="white" />
                        </View>
                    )}
                </View>

                <View style={styles.infoContainer}>
                    <Text style={styles.playlistTitle}>{playlist_name}</Text>
                    <Text style={styles.playlistDesc}>{description}</Text>
                    <Text style={styles.stats}>
                        {tracks.length} Tracks • {total_duration_mins} mins
                    </Text>
                </View>
            </View>

            {/* Action Buttons */}
            <View style={styles.actionRow}>
                <TouchableOpacity
                    style={[styles.actionBtn, { backgroundColor: '#1DB954' }]}
                    onPress={handleSaveToSpotify}
                >
                    <FontAwesome name="spotify" size={20} color="white" />
                    <Text style={styles.actionBtnText}>
                        {spotifyLinked ? "Save to Spotify" : "Connect Spotify"}
                    </Text>
                </TouchableOpacity>
                <TouchableOpacity
                    style={[styles.actionBtn, { backgroundColor: '#FF0000' }]}
                    onPress={handleSaveToYouTube}
                >
                    <FontAwesome name="youtube-play" size={20} color="white" />
                    <Text style={styles.actionBtnText}>
                        {googleLinked ? "Save to YouTube" : "Connect YouTube"}
                    </Text>
                </TouchableOpacity>
            </View>
            <View style={styles.actionRowSecondary}>
                <TouchableOpacity style={[styles.actionBtnSecondary]} onPress={handleSave}>
                    <FontAwesome name="bookmark-o" size={20} color="white" />
                    <Text style={styles.actionBtnTextSec}>Save</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.actionBtnSecondary, { backgroundColor: theme.tint, borderColor: theme.tint }]} onPress={handleShare}>
                    <FontAwesome name="share" size={20} color="white" />
                    <Text style={styles.actionBtnTextSec}>Share Story</Text>
                </TouchableOpacity>
            </View>
        </View>
    );

    return (
        <View style={styles.container}>
            <View style={styles.navBar}>
                <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                    <FontAwesome name="arrow-left" size={24} color="white" />
                </TouchableOpacity>
                <Text style={styles.navTitle}>Refine Your Vibe</Text>
                <View style={{ width: 24 }} />
            </View>

            <FlatList
                data={tracks}
                keyExtractor={(item) => item.id}
                ListHeaderComponent={renderHeader}
                renderItem={({ item, index }) => (
                    <TouchableOpacity style={styles.trackItem} onPress={() => handleTrackPress(item)}>
                        <Text style={styles.trackIndex}>{index + 1}</Text>
                        <Image
                            source={{ uri: item.album?.images[0]?.url }}
                            style={styles.trackImage}
                        />
                        <View style={styles.trackInfo}>
                            <Text style={styles.trackName} numberOfLines={1}>{item.name}</Text>
                            <Text style={styles.trackArtist}>{item.artists[0].name}</Text>

                            {/* AI Reason Badge */}
                            {item.ai_reason && (
                                <View style={styles.aiReasonBadge}>
                                    <FontAwesome name="magic" size={10} color="#A78BFA" style={{ marginRight: 4, marginTop: 2 }} />
                                    <Text style={styles.aiReasonText}>
                                        {item.ai_reason}
                                    </Text>
                                </View>
                            )}
                        </View>
                        <Text style={styles.trackDuration}>
                            {Math.floor(item.duration_ms / 60000)}:
                            {((item.duration_ms % 60000) / 1000).toFixed(0).padStart(2, '0')}
                        </Text>
                    </TouchableOpacity>
                )}
                contentContainerStyle={{ paddingBottom: 40 }}
            />

            {/* Play Modal */}
            <Modal
                animationType="fade"
                transparent={true}
                visible={modalVisible}
                onRequestClose={() => setModalVisible(false)}
            >
                <TouchableOpacity
                    style={styles.modalOverlay}
                    activeOpacity={1}
                    onPress={() => setModalVisible(false)}
                >
                    <View style={styles.modalContent}>
                        <Text style={styles.modalTitle}>Play "{selectedTrack?.name}"</Text>

                        <TouchableOpacity style={[styles.modalBtn, { backgroundColor: '#1DB954' }]} onPress={playOnSpotify}>
                            <FontAwesome name="spotify" size={24} color="white" style={{ marginRight: 10 }} />
                            <Text style={styles.modalBtnText}>Open in Spotify</Text>
                        </TouchableOpacity>

                        <TouchableOpacity style={[styles.modalBtn, { backgroundColor: '#FF0000' }]} onPress={playOnYouTube}>
                            <FontAwesome name="youtube-play" size={24} color="white" style={{ marginRight: 10 }} />
                            <Text style={styles.modalBtnText}>Search on YouTube</Text>
                        </TouchableOpacity>

                        <TouchableOpacity style={[styles.modalBtn, { backgroundColor: '#333', marginTop: 10 }]} onPress={() => setModalVisible(false)}>
                            <Text style={styles.modalBtnText}>Cancel</Text>
                        </TouchableOpacity>
                    </View>
                </TouchableOpacity>
            </Modal>

        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
    },
    navBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 60,
        paddingHorizontal: 20,
        paddingBottom: 20,
        backgroundColor: '#4c1d95',
    },
    backButton: {
        padding: 5,
    },
    navTitle: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    headerContainer: {
        padding: 20,
        paddingTop: 10,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    albumArtContainer: {
        marginRight: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
    },
    albumArt: {
        width: 120,
        height: 120,
        borderRadius: 8,
    },
    infoContainer: {
        flex: 1,
    },
    playlistTitle: {
        color: 'white',
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    playlistDesc: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 14,
        marginBottom: 10,
        lineHeight: 20,
    },
    stats: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 12,
        fontWeight: 'bold',
    },
    actionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    actionRowSecondary: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    actionBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 25,
        marginHorizontal: 5,
    },
    actionBtnSecondary: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        borderRadius: 25,
        marginHorizontal: 5,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    actionBtnText: {
        color: 'white',
        fontWeight: 'bold',
        marginLeft: 8,
    },
    actionBtnTextSec: {
        color: 'white',
        marginLeft: 8,
    },
    // Track List
    trackItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
    },
    trackIndex: {
        color: 'rgba(255,255,255,0.5)',
        width: 25,
        fontSize: 14,
    },
    trackImage: {
        width: 50,
        height: 50,
        borderRadius: 4,
        marginRight: 15,
    },
    trackInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    trackName: {
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 4,
    },
    trackArtist: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 14,
    },
    aiReasonBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(139, 92, 246, 0.1)',
        alignSelf: 'flex-start',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        marginTop: 4,
        borderWidth: 1,
        borderColor: 'rgba(139, 92, 246, 0.3)'
    },
    aiReasonText: {
        color: '#A78BFA',
        fontSize: 11,
        fontStyle: 'italic',
        flexShrink: 1, // Allow text to wrap
    },
    trackDuration: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 12,
        marginLeft: 10,
    },
    // Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '85%',
        backgroundColor: '#222',
        borderRadius: 20,
        padding: 25,
        alignItems: 'center',
    },
    modalTitle: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    modalBtn: {
        flexDirection: 'row',
        width: '100%',
        paddingVertical: 15,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    modalBtnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    refineButton: {
        marginBottom: 20,
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: "#8B5CF6",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    refineGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    refineText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    }
});
