import express from 'express';
import { initSpotifyApi } from '../middleware/spotifyAuth.js';

const router = express.Router();

// Search for tracks
router.post('/search', initSpotifyApi, async (req, res) => {
    const { query } = req.body;

    try {
        const data = await req.spotifyApi.searchTracks(query);
        res.json(data.body.tracks.items);
    } catch (error) {
        console.error('Error searching tracks:', error);
        res.status(500).json({ error: 'Failed to search tracks' });
    }
});

// Create playlist and add tracks
router.post('/playlist', initSpotifyApi, async (req, res) => {
    const { name, trackUris, coverImageUrl } = req.body;

    if (!trackUris || !Array.isArray(trackUris)) {
        return res.status(400).json({ error: 'Track URIs are required' });
    }

    // Define the operation to allow retry
    const performPlaylistCreation = async () => {
        // 1. Create Playlist
        const createData = await req.spotifyApi.createPlaylist(name || 'VibeMixer Playlist', {
            description: 'Generated by VibeMixer',
            public: false
        });
        const playlistId = createData.body.id;

        // 2. Add Tracks
        await req.spotifyApi.addTracksToPlaylist(playlistId, trackUris);

        // 3. Upload Cover Image (if provided)
        if (coverImageUrl) {
            try {
                let base64Image;

                if (coverImageUrl.startsWith('data:image')) {
                    // Extract base64 from data URL
                    base64Image = coverImageUrl.split(',')[1];
                } else {
                    console.log('Fetching cover image:', coverImageUrl);
                    const imageRes = await fetch(coverImageUrl);
                    const arrayBuffer = await imageRes.arrayBuffer();
                    const buffer = Buffer.from(arrayBuffer);
                    base64Image = buffer.toString('base64');
                }

                // Upload to Spotify
                await req.spotifyApi.uploadCustomPlaylistCoverImage(playlistId, base64Image);
                console.log('Cover image uploaded successfully');
            } catch (imgErr) {
                console.error('Failed to upload cover image:', imgErr);
                // Don't fail the whole request if image fails
            }
        }
        return createData.body;
    };

    try {
        const result = await performPlaylistCreation();
        res.json(result);
    } catch (error) {
        // Check for 401 Unauthorized
        const isAuthError = error.statusCode === 401 || (error.body && error.body.error && error.body.error.status === 401);

        if (isAuthError) {
            console.log('[Spotify Route] 401 encountered. Refreshing token and retrying...');
            try {
                // Attempt to refresh the token using the middleware helper
                if (req.refreshSpotifyToken) {
                    await req.refreshSpotifyToken();
                    // Retry operation with new token (req.spotifyApi is updated inv-place)
                    const result = await performPlaylistCreation();
                    return res.json(result);
                } else {
                    throw new Error('Refresh capability not available');
                }
            } catch (retryError) {
                console.error('[Spotify Route] Retry failed:', retryError);
                return res.status(401).json({ error: 'Session expired. Please login again.' });
            }
        }

        console.error('Error creating playlist:', error);
        res.status(500).json({ error: 'Failed to create playlist' });
    }
});

export default router;
