import express from 'express';
import SpotifyWebApi from 'spotify-web-api-node';
import dotenv from 'dotenv';

dotenv.config();

const router = express.Router();

// Middleware to initialize Spotify API with token from cookie
const initSpotifyApi = (req, res, next) => {
    const accessToken = req.cookies.spotify_access_token;

    if (!accessToken) {
        return res.status(401).json({ error: 'Not authenticated with Spotify' });
    }

    const spotifyApi = new SpotifyWebApi({
        clientId: process.env.SPOTIFY_CLIENT_ID,
        clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
    });

    spotifyApi.setAccessToken(accessToken);
    req.spotifyApi = spotifyApi;
    next();
};

// Search for tracks
router.post('/search', initSpotifyApi, async (req, res) => {
    const { query } = req.body;

    try {
        const data = await req.spotifyApi.searchTracks(query);
        res.json(data.body.tracks.items);
    } catch (error) {
        console.error('Error searching tracks:', error);
        res.status(500).json({ error: 'Failed to search tracks' });
    }
});

// Create playlist and add tracks
router.post('/playlist', initSpotifyApi, async (req, res) => {
    const { name, trackUris } = req.body;

    try {
        // 1. Get current user
        const me = await req.spotifyApi.getMe();
        const userId = me.body.id;

        // 2. Create playlist
        const playlist = await req.spotifyApi.createPlaylist(userId, {
            name: name || 'VibeMixer Playlist',
            description: 'Generated by VibeMixer AI',
        });

        // 3. Add tracks
        if (trackUris && trackUris.length > 0) {
            await req.spotifyApi.addTracksToPlaylist(playlist.body.id, trackUris);
        }

        res.json(playlist.body);
    } catch (error) {
        console.error('Error creating playlist:', error);
        res.status(500).json({ error: 'Failed to create playlist' });
    }
});

export default router;
