import express from 'express';
import { google } from 'googleapis';
import { getRegionalVibeQuery } from '../services/groq.js';

const router = express.Router();

// Middleware to initialize YouTube API client
const initYoutubeClient = async (req, res, next) => {
    console.log('[YouTube Auth] Checking tokens...');
    let accessToken = req.cookies.google_access_token;
    const refreshToken = req.cookies.google_refresh_token;

    const oauth2Client = new google.auth.OAuth2(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET,
        'http://127.0.0.1:4000/auth/google/callback'
    );

    if (!accessToken && !refreshToken) {
        return res.status(401).json({ error: 'Not authenticated with Google' });
    }

    if (!accessToken && refreshToken) {
        try {
            console.log('[YouTube Auth] Refreshing token...');
            oauth2Client.setCredentials({ refresh_token: refreshToken });
            const { credentials } = await oauth2Client.refreshAccessToken();
            accessToken = credentials.access_token;

            res.cookie('google_access_token', accessToken, {
                httpOnly: true,
                secure: process.env.NODE_ENV === 'production',
                maxAge: (credentials.expiry_date - Date.now()),
                path: '/',
                sameSite: 'lax'
            });
        } catch (error) {
            console.error('Google Token Refresh Error:', error);
            return res.status(401).json({ error: 'Session expired' });
        }
    }

    oauth2Client.setCredentials({ access_token: accessToken });
    req.youtube = google.youtube({ version: 'v3', auth: oauth2Client });
    next();
};

// Create Playlist and Add Tracks
router.post('/playlist', initYoutubeClient, async (req, res) => {
    const { name, description, tracks } = req.body;

    if (!tracks || !Array.isArray(tracks)) {
        return res.status(400).json({ error: 'Tracks are required' });
    }

    try {
        // 1. Create Playlist
        console.log(`Creating YouTube playlist: ${name}`);
        const playlistRes = await req.youtube.playlists.insert({
            part: ['snippet', 'status'],
            requestBody: {
                snippet: {
                    title: name,
                    description: description || 'Generated by VibeMixer',
                },
                status: {
                    privacyStatus: 'private', // Default to private for safety
                },
            },
        });

        const playlistId = playlistRes.data.id;
        console.log(`Playlist created: ${playlistId}`);

        // 2. Search and Add Videos
        const videoIds = [];
        for (const track of tracks) {
            try {
                // Search for "Song Name Artist Name Official Video"
                const query = `${track.name} ${track.artists[0].name} Official Video`;
                const searchRes = await req.youtube.search.list({
                    part: ['snippet'],
                    q: query,
                    maxResults: 1,
                    type: 'video',
                });

                if (searchRes.data.items.length > 0) {
                    const videoId = searchRes.data.items[0].id.videoId;
                    videoIds.push(videoId);
                }
            } catch (err) {
                console.error(`Failed to find video for ${track.name}:`, err);
            }
        }

        // 3. Add videos to playlist (YouTube API requires adding one by one)
        // We'll do it sequentially to avoid rate limits
        for (const videoId of videoIds) {
            try {
                await req.youtube.playlistItems.insert({
                    part: ['snippet'],
                    requestBody: {
                        snippet: {
                            playlistId: playlistId,
                            resourceId: {
                                kind: 'youtube#video',
                                videoId: videoId,
                            },
                        },
                    },
                });
            } catch (err) {
                console.error(`Failed to add video ${videoId}:`, err);
            }
        }

        res.json({
            message: 'Playlist created successfully',
            playlistUrl: `https://www.youtube.com/playlist?list=${playlistId}`,
            playlistId: playlistId
        });

    } catch (error) {
        console.error('YouTube API Error:', error);
        res.status(500).json({ error: 'Failed to create YouTube playlist' });
    }
});

// Search for Regional Vibe (AI Optimized Search)
router.get('/region-vibe', async (req, res) => {
    const { region } = req.query;

    if (!region) {
        return res.status(400).json({ error: 'Region is required' });
    }

    try {
        console.log(`[Region Vibe] Request for region: ${region}`);

        const youtube = google.youtube({
            version: 'v3',
            auth: process.env.GOOGLE_API_KEY
        });

        // 1. Get AI Optimized Query
        let searchQuery = `Best ${region} songs india`; // Default
        try {
            const aiData = await getRegionalVibeQuery(region);
            if (aiData.searchQuery) {
                searchQuery = aiData.searchQuery;
            }
        } catch (e) {
            console.error('AI Curation failed, using default query', e);
        }

        // 2. Search YouTube (Single Request = 100 Quota Units)
        console.log(`[Region Vibe] Searching YouTube with query: "${searchQuery}"`);

        const searchRes = await youtube.search.list({
            part: ['snippet'],
            q: searchQuery,
            maxResults: 20, // Fetch more to allow filtering
            type: 'video',
        });

        if (searchRes.data.items.length > 0) {
            // Filter out Mashups, Jukeboxes, and Compilations
            const bannedWords = ['mashup', 'jukebox', 'nonstop', 'collection', 'compilation', 'mix', 'dj'];

            let videos = searchRes.data.items
                .filter(item => {
                    const title = item.snippet.title.toLowerCase();
                    return !bannedWords.some(word => title.includes(word));
                })
                .map(item => ({
                    id: item.id.videoId,
                    title: item.snippet.title,
                    thumbnail: item.snippet.thumbnails.medium.url,
                    channelTitle: item.snippet.channelTitle
                }));

            // If filtering removed too many, fill back up with original results (to ensure we show something)
            if (videos.length < 5) {
                console.log('[Region Vibe] Strict filtering removed too many videos. Relaxing filter.');
                videos = searchRes.data.items.map(item => ({
                    id: item.id.videoId,
                    title: item.snippet.title,
                    thumbnail: item.snippet.thumbnails.medium.url,
                    channelTitle: item.snippet.channelTitle
                }));
            }

            // Limit to 10
            return res.json({ videos: videos.slice(0, 10) });
        }

        res.status(404).json({ error: 'No vibe found' });

    } catch (error) {
        console.error('YouTube Search Error:', error);
        // Check for Quota Error specifically
        if (error.code === 403 && error.message.includes('quota')) {
            return res.status(403).json({ error: 'YouTube API Quota Exceeded. Please try again tomorrow.' });
        }
        res.status(500).json({ error: 'Failed to search YouTube', details: error.message });
    }
});

export default router;
