
import React, { useState } from 'react';
import { StyleSheet, Dimensions, Image, TouchableOpacity, ScrollView, ActivityIndicator, Linking, Alert } from 'react-native';
import { Text, View } from '@/components/Themed';
import Colors from '@/constants/Colors';
import { useColorScheme } from '@/components/useColorScheme';
import { LinearGradient } from 'expo-linear-gradient';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import IndiaMapWeb from '@/components/IndiaMapWeb';
import { api } from '@/constants/api';
import { useAuth } from '@/context/AuthContext';
import { router } from 'expo-router';

const { width } = Dimensions.get('window');

interface VideoResult {
    id: string;
    title: string;
    thumbnail: string;
    channelTitle: string;
}

export default function MapScreen() {
    const colorScheme = useColorScheme();
    const { googleLinked, loginWithGoogle } = useAuth();

    const [selectedRegion, setSelectedRegion] = useState<string | null>(null);
    const [videos, setVideos] = useState<VideoResult[]>([]);
    const [loading, setLoading] = useState(false);
    const [creatingPlaylist, setCreatingPlaylist] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleRegionSelect = async (regionName: string) => {
        console.log("Region selected:", regionName);
        setSelectedRegion(regionName);
        setLoading(true);
        setError(null);
        setVideos([]);

        try {
            // Fetch vibes for the region
            const response = await api.get(`/youtube/region-vibe?region=${encodeURIComponent(regionName)}`);
            if (response && response.videos) {
                setVideos(response.videos);
            } else {
                setError('No vibes found for this region.');
            }
        } catch (err: any) {
            console.error("Failed to fetch region vibe:", err);
            setError('Failed to load vibes. Only valid Indian states are supported.');
        } finally {
            setLoading(false);
        }
    };

    const openVideo = (videoId: string) => {
        Linking.openURL(`https://www.youtube.com/watch?v=${videoId}`);
    };

    const handleCreatePlaylist = async () => {
        if (!selectedRegion || videos.length === 0) return;

        if (!googleLinked) {
            Alert.alert(
                "Connect YouTube",
                "You need to link your Google account to create playlists.",
                [
                    { text: "Cancel", style: "cancel" },
                    { text: "Connect", onPress: loginWithGoogle }
                ]
            );
            return;
        }

        setCreatingPlaylist(true);
        try {
            const payload = {
                name: `Vibe of ${selectedRegion}`,
                description: `A curated collection of top tracks from ${selectedRegion}. Generated by VibeMixer.`,
                tracks: videos.map(v => ({
                    name: v.title,
                    videoId: v.id, // Providing ID saves quota on backend
                    artists: [{ name: v.channelTitle }]
                }))
            };

            const response = await api.post('/youtube/playlist', payload);

            if (response.error) {
                throw new Error(response.message || "Failed to create playlist");
            }

            Alert.alert(
                "Success! 🎉",
                `Playlist "Vibe of ${selectedRegion}" created on your YouTube channel!`,
                [
                    { text: "Open Playlist", onPress: () => Linking.openURL(response.playlistUrl) },
                    { text: "OK" }
                ]
            );

        } catch (err: any) {
            console.error("Playlist creation failed:", err);
            Alert.alert("Error", "Failed to save playlist. Please try again.");
        } finally {
            setCreatingPlaylist(false);
        }
    };

    return (
        <View style={styles.container}>
            {/* Global Background */}
            <LinearGradient
                colors={['#000000', '#1a1033']}
                style={StyleSheet.absoluteFill}
            />

            <ScrollView contentContainerStyle={styles.scrollContent}>

                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Indian Vibe Map</Text>
                    <Text style={styles.subtitle}>
                        Touch a state to discover its unique musical soul.
                    </Text>
                </View>

                {/* Map Container */}
                <View style={styles.mapContainer}>
                    <IndiaMapWeb onRegionSelect={handleRegionSelect} />
                </View>

                {/* Results Section */}
                <View style={styles.resultsContainer}>
                    {selectedRegion && (
                        <View style={styles.regionHeader}>
                            <FontAwesome name="map-marker" size={20} color="#FF5533" />
                            <Text style={styles.regionTitle}>{selectedRegion}</Text>
                        </View>
                    )}

                    {loading && (
                        <View style={styles.loadingContainer}>
                            <ActivityIndicator size="large" color="#FF5533" />
                            <Text style={styles.loadingText}>Curating {selectedRegion}'s Vibe...</Text>
                        </View>
                    )}

                    {error && (
                        <View style={styles.errorContainer}>
                            <FontAwesome name="exclamation-circle" size={24} color="#EF4444" />
                            <Text style={styles.errorText}>{error}</Text>
                        </View>
                    )}

                    {!loading && videos.length > 0 && (
                        <>
                            <TouchableOpacity
                                style={[styles.saveButton, creatingPlaylist && styles.saveButtonDisabled]}
                                onPress={handleCreatePlaylist}
                                disabled={creatingPlaylist}
                            >
                                {creatingPlaylist ? (
                                    <ActivityIndicator color="white" />
                                ) : (
                                    <>
                                        <FontAwesome name="youtube-play" size={20} color="white" />
                                        <Text style={styles.saveButtonText}>Save as Playlist</Text>
                                    </>
                                )}
                            </TouchableOpacity>

                            <View style={styles.videoGrid}>
                                {videos.map((video) => (
                                    <TouchableOpacity
                                        key={video.id}
                                        style={styles.videoCard}
                                        onPress={() => openVideo(video.id)}
                                        activeOpacity={0.8}
                                    >
                                        <Image source={{ uri: video.thumbnail }} style={styles.thumbnail} />
                                        <View style={styles.playOverlay}>
                                            <FontAwesome name="play-circle" size={40} color="rgba(255,255,255,0.9)" />
                                        </View>
                                        <View style={styles.videoInfo}>
                                            <Text style={styles.videoTitle} numberOfLines={2}>{video.title}</Text>
                                            <Text style={styles.channelTitle}>{video.channelTitle}</Text>
                                        </View>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        </>
                    )}

                    {!selectedRegion && !loading && (
                        <View style={styles.placeholderContainer}>
                            <FontAwesome name="music" size={40} color="rgba(255,255,255,0.1)" />
                            <Text style={styles.placeholderText}>Select a region to start</Text>
                        </View>
                    )}
                </View>

            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40,
    },
    header: {
        alignItems: 'center',
        paddingVertical: 30,
        paddingHorizontal: 20,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FF5533', // Map highlight color
        marginBottom: 8,
        textAlign: 'center',
    },
    subtitle: {
        color: 'rgba(255,255,255,0.6)',
        textAlign: 'center',
        fontSize: 16,
    },
    mapContainer: {
        height: 420, // Slightly more than WebView height
        width: '100%',
        alignItems: 'center',
        marginBottom: 20,
    },
    resultsContainer: {
        paddingHorizontal: 20,
        minHeight: 300,
    },
    regionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        gap: 10,
    },
    regionTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
    },
    loadingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
        gap: 15,
    },
    loadingText: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 16,
    },
    errorContainer: {
        alignItems: 'center',
        padding: 40,
        gap: 10,
    },
    errorText: {
        color: '#EF4444',
        fontSize: 16,
        textAlign: 'center',
    },
    saveButton: {
        flexDirection: 'row',
        backgroundColor: '#FF0000',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 20,
    },
    saveButtonDisabled: {
        opacity: 0.7,
    },
    saveButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    videoGrid: {
        gap: 20,
    },
    videoCard: {
        backgroundColor: '#1E1E1E',
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 0,
    },
    thumbnail: {
        width: '100%',
        height: 200,
        resizeMode: 'cover',
    },
    playOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 200,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.1)',
    },
    videoInfo: {
        padding: 15,
    },
    videoTitle: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
        lineHeight: 22,
    },
    channelTitle: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
    },
    placeholderContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 60,
        gap: 15,
        opacity: 0.5,
    },
    placeholderText: {
        color: 'white',
        fontSize: 16,
    }
});
